apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: messager-prod
resources:
  - ../../base
  - namespace.yaml
  - pvc.yaml
  - pv.yaml
labels:
  - pairs:
      environment: prod
patches:
  - path: patches/replicas.yaml
  - path: patches/resources.yaml
  - path: patches/csi-secret.yaml
  - path: patches/frontend-port.yaml
images:
  - name: mablinov2704/frontend
    newTag: latest
  - name: mablinov2704/bff
    newTag: latest
  - name: mablinov2704/user-service
    newTag: latest
  - name: mablinov2704/message-service
    newTag: latest