apiVersion: v1
kind: PersistentVolume
metadata:
  name: uploads-pv
spec:
  mountOptions:
    - url=http://minio.messager-prod.svc.cluster.local:9000
  csi:
    nodePublishSecretRef:
      name: csi-s3-secret-prod
      namespace: messager-prod
    volumeHandle: uploads-prod
    nodeStageSecretRef:
      name: csi-s3-secret-prod
      namespace: messager-prod
    volumeAttributes:
      bucket: uploads-prod
      endpoint: http://minio.messager-prod.svc.cluster.local:9000