apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: messager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: workload
                    operator: In
                    values:
                      - app
      containers:
        - name: user-service
          image: mablinov2704/user-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: messager-config
                  key: USER_HTTP_PORT
            - name: DB_DSN
              valueFrom:
                secretKeyRef:
                  name: messager-db-secret
                  key: USER_DB_DSN