apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-messages
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: wait-for-postgres
          image: postgres:16-alpine
          command:
            - sh
            - -c
            - |
              until pg_isready -h postgres -p 5432 -U messager; do
                echo "Waiting for postgres..."
                sleep 2
              done
      containers:
        - name: migrate-messages
          image: ghcr.io/kukymbr/goose-docker:latest
          env:
            - name: GOOSE_DRIVER
              value: postgres
            - name: GOOSE_DBSTRING
              value: "host=postgres user=messager password=messager dbname=messager_messages sslmode=disable"
            - name: GOOSE_MIGRATION_DIR
              value: /migrations
          volumeMounts:
            - name: migrations
              mountPath: /migrations
      volumes:
        - name: migrations
          configMap:
            name: messages-migrations-cm