apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: workload
                    operator: In
                    values:
                      - app
      containers:
        - name: frontend
          image: mablinov2704/frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: BFF_URL
              valueFrom:
                configMapKeyRef:
                  name: messager-config
                  key: FRONTEND_BFF_URL
            - name: BFF_INTERNAL_URL
              valueFrom:
                configMapKeyRef:
                  name: messager-config
                  key: FRONTEND_BFF_INTERNAL_URL