apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csi-s3-volumeattachment-status
rules:
  - apiGroups:
      - storage.k8s.io
    resources:
      - volumeattachments/status
    verbs:
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csi-s3-volumeattachment-status
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: csi-s3-volumeattachment-status
subjects:
  - kind: ServiceAccount
    name: csi-attacher-sa
    namespace: kube-system