apiVersion: v1
kind: PersistentVolume
metadata:
  name: uploads-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - allow-delete
    - url=http://minio.messager.svc.cluster.local:9000
    - use_path_request_style
  csi:
    driver: ch.ctrox.csi.s3-driver
    volumeHandle: uploads
    nodePublishSecretRef:
      name: csi-s3-secret
      namespace: messager
    nodeStageSecretRef:
      name: csi-s3-secret
      namespace: messager
    volumeAttributes:
      endpoint: http://minio.messager.svc.cluster.local:9000
      bucket: uploads
      mounter: rclone
  storageClassName: ""