apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb
data:
  01-create-service-databases.sql: |
    CREATE DATABASE messager_users;
    CREATE DATABASE messager_messages;
    GRANT ALL PRIVILEGES ON DATABASE messager_users TO messager;
    GRANT ALL PRIVILEGES ON DATABASE messager_messages TO messager;