apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: messager-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yyeart/lab-k8s-messager
    targetRevision: HEAD
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: messager-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      