apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
labels:
  - pairs:
      environment: dev
patches:
  - path: patches/replicas.yaml
  - path: patches/resources.yaml
  - path: patches/ingress-host.yaml

images:
  - name: mablinov2704/frontend
    newTag: latest
  - name: mablinov2704/bff
    newTag: latest
  - name: mablinov2704/user-service
    newTag: latest
  - name: mablinov2704/message-service
    newTag: latest