apiVersion: v1
kind: PersistentVolume
metadata:
  name: uploads-pv
  namespace: messager
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - allow-delete
    - use_path_request_style
    - url=http://minio.messager.svc.cluster.local:9000
    - region=""
  csi:
    driver: ch.ctrox.csi.s3-driver
    volumeHandle: uploads
    nodePublishSecretRef:
      name: csi-s3-secret
      namespace: messager
    nodeStageSecretRef:
      name: csi-s3-secret
      namespace: messager
    volumeAttributes:
      bucketName: uploads
      bucket: uploads
      endpoint: http://minio.messager.svc.cluster.local:9000
      region: ""
      mounter: s3fs
  storageClassName: ""